Repository mapbender/mapbender, pull requests merged in 2018-04, with the labels that each got.

#711 Feature/repeatable cli print
  src/Mapbender/PrintBundle/Command/RunJobCommand.php
  src/Mapbender/PrintBundle/Component/ImageExportService.php
  src/Mapbender/PrintBundle/Component/PrintService.php
Labels: Feature

#748 Feature/introspections for sources <=> applications <=> sourcinstances
  src/Mapbender/IntrospectionBundle/Command/ElementClassesCommand.php
  src/Mapbender/IntrospectionBundle/Command/SourcesCommand.php
  src/Mapbender/IntrospectionBundle/Component/Aggregator/Application.php
  src/Mapbender/IntrospectionBundle/Component/Aggregator/Base.php
  src/Mapbender/IntrospectionBundle/Component/Aggregator/Relation/ApplicationToSources.php
  src/Mapbender/IntrospectionBundle/Component/Aggregator/Relation/SourceToApplications.php
  src/Mapbender/IntrospectionBundle/Component/Aggregator/Relation/SourceToSourceInstances.php
  src/Mapbender/IntrospectionBundle/Component/Aggregator/Source.php
  src/Mapbender/IntrospectionBundle/Component/Collector.php
  src/Mapbender/IntrospectionBundle/Component/WorkingSet.php
  src/Mapbender/IntrospectionBundle/Entity/Utils/Command/DataItem.php
  src/Mapbender/IntrospectionBundle/Entity/Utils/Command/DataItemFormatting.php
  src/Mapbender/IntrospectionBundle/Entity/Utils/Command/DataItemList.php
  src/Mapbender/IntrospectionBundle/Entity/Utils/Command/DataTreeNode.php
  src/Mapbender/IntrospectionBundle/Entity/Utils/Command/JsonFormatting.php
  src/Mapbender/IntrospectionBundle/Entity/Utils/Command/YamlFormatting.php
  src/Mapbender/IntrospectionBundle/Utils/BundleUtil.php
Labels: Enhancement, QoL

#798 Fix basesourceswitcher automatically opening on startup
  src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
Labels: Bug

#819 Fix BSS menu not closing after selection
  src/Mapbender/CoreBundle/Resources/public/mapbender.element.basesourceswitcher.js
Labels: Bug, Important
