Repository mapbender/mapbender, pull requests merged in 2018-03, with the labels that each got.

#775 Fix/add axis order performance
  src/Mapbender/CoreBundle/Resources/public/mapbender.element.map.mapaxisorder.js
Labels: Performance

#784 Enhancement/form validators
  src/Mapbender/CoreBundle/Element/Type/HTMLElementAdminType.php
  src/Mapbender/CoreBundle/Form/Type/HtmlFormType.php
  src/Mapbender/CoreBundle/Resources/config/constraints.yml
  src/Mapbender/CoreBundle/Resources/config/formTypes.yml
  src/Mapbender/CoreBundle/Validator/Constraints/TwigConstraintValidator.php
Labels: Enhancement

#793 Fix/form types as services
  src/Mapbender/CoreBundle/Component/Element.php
  src/Mapbender/CoreBundle/DependencyInjection/MapbenderCoreExtension.php
  src/Mapbender/CoreBundle/Resources/config/formTypes.yml
Labels: Bug
